### ISSUE TITLE
@ZasticBradyn

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Snowflake-Coder-H2o/Organized-blooket-Hacks#1]
@ZasticBradyn Hey I need some help making these new hacks. If you could help me that would be great!

-Snow

**Comment by Snowflake-Coder-H2o** [comment]
@zasticbraydn

**Comment by ZasticBradyn** [comment]
sorry but im not really making blooket hacks publicly anymore bcuz gliz is just, let's say he is something

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn We can make the hacks private. It dosent matter if he is trying anything. you coded it all. He made my take down a whole entire repo. I dont care what gliz says.

**Comment by Dogwaterzx** [comment]
WOAHHHH SLAYY QUEEEEEN

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Hey you made hacks on your repo? Can you help me get mine back up?

**Comment by ZasticBradyn** [comment]
I'm honestly not that motivated right now, maby in a month or a couple of weeks I can help but i have alot of personal stuff going on rn

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Ok man take a couple days to yourslef.

**Comment by ZasticBradyn** [comment]
thanks for understanding

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn No problem man. Im here for you, we're friends.that what they do

**Comment by ZasticBradyn** [comment]
mind inviting me to the repo again? @Snowflake-Coder-H2o

**Comment by Snowflake-Coder-H2o** [comment]
yes sure @ZasticBradyn

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Hey are you able to help me out with this repo?

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn You mind helping me with this repo??

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn ??
