### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [Snowflake-Coder-H2o/Organized-blooket-Hacks#2]
@Treefire33 delete the repo that your forked from me please

**Comment by Treefire33** [comment]
Did it.

**Comment by ZasticBradyn** [comment]
> @Treefire33 delete the repo that your forked from me please

honestly forks make ur repo apear higher up when u search for blooket hacks, so i wouldnt ask people to remove them. but thats ur choice

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Oh ok
