### ISSUE TITLE
Fix….

### ISSUE THREAD

**Issue by coolman3289** [Snowflake-Coder-H2o/Organized-blooket-Hacks#3]
Please fix and keep us updated on the fixing status.

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 Me and @ZasticBradyn Are currently working on this

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 Not 100% sure

**Comment by coolman3289** [comment]
Okay. Please give me another comment when done.

**Comment by coolman3289** [comment]
Also non of these are gxlizzies righ?

**Comment by ZasticBradyn** [comment]
> Also non of these are gxlizzies righ?

no.

fuck gliz

**Comment by coolman3289** [comment]
Yoooo, what you got against gliz?

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 He made me take down a whole repo, and still coming at me for apparently using his hacks it was me and zatic's code

**Comment by coolman3289** [comment]
:(

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 Yeah so that is why nothing works rn

**Comment by coolman3289** [comment]
Why so that why? If you do not use her code, why would what she does effect you.

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 Why you say her? Gliz is a guy right?

**Comment by coolman3289** [comment]
Maybe? But why would what she did causes your hacks to stop working?

**Comment by coolman3289** [comment]
How could they “make you”

**Comment by Snowflake-Coder-H2o** [comment]
@coolman3289 becuase they thought it was their code so they said delete it or they will file DMCA takedown. So I just deleted it. But Im remaking my hacks

**Comment by coolman3289** [comment]
Okay, hopefully you will be able to recover most of the code.
